Feature: Input component
devjasha/travel-tale pull request #6
Opened 2024-05-18 13:48 UTC by Obichris11

kann sein, dass das noch nicht ganz fertig ist gerade mit dem styling. Also gerne Verbesserungsvorschläge gönnen ^^

2024-05-18 14:01 UTC, devjasha requested changes
Found a little bit. I think in the future we have to rework it a little, because we need some server action and for that some functionality, like onClick and onBlur. Stuff like that.

2024-05-18 14:01 UTC, devjasha commented on apps/web/app/page.tsx
> +      {/* DELETE ME */}
Delete comment

2024-05-18 14:01 UTC, devjasha commented on apps/web/app/page.tsx
> +      <Input inputType={"text"} inputName={"InputTest"} inputPlaceholder={"Placeholder"}>Title</Input>
Remove Component after testing

2024-05-18 14:01 UTC, devjasha commented on apps/web/app/page.tsx
> +      <Input inputType={"text"} inputName={"InputTest"} inputPlaceholder={"Placeholder"}>Title</Input>
When you add props to the Component and if the value will be a string then you can get rid of the brackets. Looks something like this:

`inputType="text"`

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.tsx
> +    inputType: string;
don't need to put `input` in front of every prop. Because the props are scoped inside the component

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.tsx
> +    children: any;
You dont need a children prop

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.tsx
> +    children,
You dont need a children prop

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.tsx
> +            <label className={styles.inputLabel} htmlFor={inputName}>{children}</label>
Why using a children prop. A children prop are you using when there will be different Elements inside the label. But thats not the case here. Just use a props like `label` from type string

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.module.scss
> +    inline-size: 150px;
Why using a fixed with. Let the component always grow the big as it can.

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.module.scss
> +    padding-bottom: 2px;
use logical properties. `padding-inline-start` and `padding-block-end`

2024-05-18 14:01 UTC, devjasha commented on apps/web/components/elements/InputField/Input.module.scss
> +    block-size: 20px;
Why `block-size`?

2024-05-18 14:01 UTC, devjasha commented on apps/web/app/page.tsx
> +import Input from "@/components/elements/InputField/Input";
Remove input after testing

2024-05-18 15:15 UTC, Obichris11 commented on apps/web/components/elements/InputField/Input.tsx
> +    inputType: string;
Thats true, makes only sense when you have multiple components with similar props. That way have the same naming convention for different Elements :)

2024-05-18 15:27 UTC, Obichris11 commented on apps/web/components/elements/InputField/Input.module.scss
> +    inline-size: 150px;
Like... change to auto? 🤔

2024-05-18 15:36 UTC, devjasha commented on apps/web/components/elements/InputField/Input.module.scss
> +    inline-size: 150px;
100%

2024-05-22 18:22 UTC, devjasha approved these changes
LGTM

2024-05-22 18:22 UTC, merged