Feat: c-PostUser
devjasha/travel-tale pull request #7
Opened 2024-05-18 13:54 UTC by moritzro

## This PR adds:
* new component to display User Information on a new post

2024-05-18 14:04 UTC, devjasha requested changes
Nice work. In the future we can discuss if we want to change that component to a client component. I think it would make sense. What are you saying?

2024-05-18 14:04 UTC, devjasha commented on apps/web/components/custom/PostUser/PostUser.module.scss
> +  width: fit-content;
use logical properties. `inline-size`

2024-05-22 18:46 UTC, moritzro commented on apps/web/components/custom/PostUser/PostUser.module.scss
> +  width: fit-content;
Changed it to logical properties.

2024-05-23 08:44 UTC, devjasha approved these changes

2024-05-23 08:44 UTC, merged